'use client'

import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "./components/Navbar";
import ReactQueryWrapper from "./reactQuery";
const inter = Roboto({ subsets: ["greek"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en"> 
      <body className={inter.className} suppressHydrationWarning={true}>
        <header className="max-w-[1920px] m-auto">
          <Navbar />
        </header>
        <ReactQueryWrapper>{children}</ReactQueryWrapper>
      </body>
    </html>

  );
}
